import MyContext  from '@/Helper/Context';
import './globals.css';

export const metadata = {
  title: 'Mine React App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  MyContext
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {children}
        {/* <MyContext>
          {children}
        </MyContext> */}
      </body>
    </html>
  );
};
